#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 28 14:52:17 ICT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.7.1.zip
enableShaders=false
